### ISSUE TITLE
Argoverse 2 Scene Flow generation script link 404

### ISSUE THREAD

**Issue by mackery** [kylevedder/zeroflow#1]
in the getting start ,I need the link https://github.com/nchodosh/argoverse2-sf to compute ground truth flows ,but it's 404.how can i generate the flows?

**Comment by MaxtuneLee** [comment]
Met the same issue, any solution?

**Comment by kylevedder** [comment]
Nate said he'd make the repo public today. I'll let you know when it's public.

**Comment by kylevedder** [comment]
I cloned the repo and made it public to get you unblocked immediately:

https://github.com/kylevedder/argoverse2-sf

**Comment by mackery** [comment]
> I cloned the repo and made it public to get you unblocked immediately:
> 
> https://github.com/kylevedder/argoverse2-sf

Thanks a lot.

**Comment by kylevedder** [comment]
I updated the `GETTING_STARTED.md` link to point to this new repo, and updated the text a little bit to clarify that the files stored on the Argoverse EC2 bucket may be in a slightly different directory format (they keep changing) so you should make sure that it conforms to the file layout specified in the `GETTING_STARTED.md` file. 

An example of how to use tool (with a bit of stuff specific to our SLURM cluster) can be found here:

https://github.com/kylevedder/argoverse2-sf/blob/main/launch_slurm_validation.sh

The docker image I used to run everything was built using the `Dockerfile` in the repo, and it can be pulled from

https://hub.docker.com/repository/docker/kylevedder/argoverse2_sf/general

**Comment by kylevedder** [comment]
Closing

**Comment by kylevedder** [comment]
Closing

**Comment by kylevedder** [comment]
Since you both seem interested in trying out my code, I just uploaded all of my pretrained model weights for the paper to this repo: 

https://github.com/kylevedder/zeroflow_weights

I've also updated all the documentation to point to this for future reference.
