### ISSUE TITLE
Running outside of a docker

### ISSUE THREAD

**Issue by deeptibhegde** [kylevedder/zeroflow#5]
Is there a way to set up the environment and run the demo on argoverse without a Docker setup? For example, could I have a list of the environment dependencies and build instructions so that I can run it normally?

**Comment by kylevedder** [comment]
The [Dockerfile](https://github.com/kylevedder/zeroflow/blob/803a87c878c5569be68cd4c333dfe0bf16029d24/docker/Dockerfile) fully specifies the environment we used.

**Comment by kylevedder** [comment]
Sorry I didn't mean to close this issue. Let me know if this resolves your issues.

**Comment by deeptibhegde** [comment]
I was able to run the demo using the environment specifications mentioned in the linked file, thank you.
